Support for playwright test runner #72
felixjb/testify pull request #73
Opened 2021-06-18 12:15 UTC by roggenbrot

Fixes: #72

2021-06-24 08:42 UTC, roggenbrot commented
Any updates?

2021-06-30 13:51 UTC, felixjb requested changes

2021-06-30 13:51 UTC, felixjb commented on src/runners/PlaywrightTestRunner.ts
> +    });*/
If the code does not do anything useful, I think it should not be commited to the repo.

2021-06-30 13:54 UTC, felixjb commented
Hi @roggenbrot sorry I took so long to respond. 

How much of the "test runner market share" does playwright owns? I am worried about having to maintain compatibility with many test runners. as it adds a lot of complexity to the next steps of the project.

2021-07-01 08:42 UTC, roggenbrot commented
>How much of the "test runner market share" does playwright owns?

playwright test will be replacing jest for e2 testing in the coming months, believe me.

I can give to a demo, or explain you the benefits in details during a chat

>  I am worried about having to maintain compatibility with many test runners

Syntax is equal to jest. So at least for the parser part no real playwright specific changes are required

2021-07-01 14:03 UTC, felixjb commented
Alright! Seems like a good idea then. Do you have a discord account? We can chat from there if you want: felixjb#6049

2021-07-23 13:25 UTC, felixjb approved these changes

2021-07-23 13:25 UTC, merged